### ISSUE TITLE
Support for DMD 2.086.0

### ISSUE THREAD

**Issue by ZaDarkSide** [Abscissa/scriptlike#38]
Please add support for latest DMD 2.086.0

**Comment by Abscissa** [comment]
Is there a specific incompatibility or breakage on that version?

**Comment by ZaDarkSide** [comment]
```
scriptlike 0.10.2: building configuration "library"...
C:\Users\Dell\AppData\Local\dub\packages\scriptlike-0.10.2\scriptlike\src\scriptlike\path\extras.d(25,8): Error: module `std.path` member osDefaultCaseSensitivity is not visible from module extras
C:\Users\Dell\AppData\Local\dub\packages\scriptlike-0.10.2\scriptlike\src\scriptlike\path\wrappers.d(26,15): Error: module `std.path` member osDefaultCaseSensitivity is not visible from module wrappers
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

**Comment by ZaDarkSide** [comment]
I think it is already fixed in this commit https://github.com/Abscissa/scriptlike/commit/91d6d46d1b3dbeb8e12e7996bc4924bd165ccba1 but the releases wasn't yet incremented so dub fetches the latest version that hasn't the fix applied, version 0.10.2 is from Mar 3, 2017 so a year has passed from last release, maybe it is time for another release which will include all fixes?

**Comment by WebFreak001** [comment]
can we get a new release tag @Abscissa ? It all seems to work fine in `2.087.0` using ~master

**Comment by Abscissa** [comment]
Ahh, right. Thanks for the ping, and sorry about the delay. New release is up and tagged now: v0.10.3
